const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const screens=[['home','Health Home','ภาพรวม'],['timeline','ประวัติสุขภาพ',''],['add','เพิ่มบันทึก',''],['vaccines','วัคซีน','ติดตามสุขภาพ'],['meds','ยา & การให้ยา',''],['appointments','นัดหมาย',''],['weight','น้ำหนัก & BCS',''],['labs','ผลแล็บ',''],['allergies','แพ้ & การวินิจฉัย',''],['documents','เอกสาร',''],['share','แชร์ข้อมูลสุขภาพ','ความเป็นส่วนตัว'],['shares','สิทธิ์ที่แชร์อยู่',''],['verification','ศูนย์การยืนยัน',''],['emergency','Emergency Card',''],['insurance','ประกันสัตว์เลี้ยง','เพิ่มเติม'],['nutrition','โภชนาการ',''],['access','ผู้มีสิทธิ์ดูแล',''],['notifications','ตั้งค่าการแจ้งเตือน','']];
const types={vaccine:'วัคซีน',medication:'ยา',weight:'น้ำหนัก',lab:'ผลแล็บ',allergy:'การแพ้',diagnosis:'การวินิจฉัย',visit:'พบสัตวแพทย์',surgery:'ผ่าตัด',note:'บันทึก'};
const marks={vaccine:'shield',medication:'heart',weight:'tune',lab:'file',allergy:'shield',diagnosis:'file',visit:'pin',surgery:'heart',note:'file'};
const petData=[{id:'pet_mochi',name:'Mochi',kind:'dog',breed:'Golden Retriever',age:'2 ปี 4 เดือน'},{id:'pet_luna',name:'Luna',kind:'cat',breed:'British Shorthair',age:'1 ปี 8 เดือน'}];
function fresh(){return {page:'home',doc:'flow',pet:'pet_mochi',role:'owner',mode:'normal',clock:new Date('2026-09-07T09:00:00+07:00').getTime(),next:20,filter:{type:'all',provenance:'all',from:'',to:''},formType:'vaccine',edit:null,amend:null,records:[
 {id:'r1',pet:'pet_mochi',type:'vaccine',title:'วัคซีนพิษสุนัขบ้า',date:'2026-08-18',provenance:'Vet verified',verified:true,due:'2027-08-18',provider:'คลินิกบ้านเพื่อนสัตว์',notes:'ข้อมูลจำลองจากสมุดวัคซีน',reminder:true},
 {id:'r2',pet:'pet_mochi',type:'medication',title:'ยาตัวอย่าง A',date:'2026-09-05',provenance:'Owner entered',dose:'1',unit:'เม็ด',frequency:'วันละครั้ง 18:00',end:'2026-09-12',status:'active',notes:'ตัวอย่างตารางที่เจ้าของบันทึก ไม่ใช่คำแนะนำยา',reminder:true},
 {id:'r3',pet:'pet_mochi',type:'weight',title:'บันทึกน้ำหนัก',date:'2026-08-01',provenance:'Owner entered',value:24.8},
 {id:'r4',pet:'pet_mochi',type:'weight',title:'บันทึกน้ำหนัก',date:'2026-08-20',provenance:'Owner entered',value:25.1},
 {id:'r5',pet:'pet_mochi',type:'weight',title:'บันทึกน้ำหนัก',date:'2026-09-06',provenance:'Owner entered',value:25.4},
 {id:'r6',pet:'pet_mochi',type:'lab',title:'CBC · ตรวจประจำปี',date:'2026-08-18',provenance:'Vet verified',verified:true,test:'ค่าตัวอย่าง X',result:18.2,unit:'หน่วยตัวอย่าง',low:5,high:17,notes:'ผลและช่วงอ้างอิงทั้งหมดเป็นข้อมูลจำลอง ไม่ใช้ตีความสุขภาพ'},
 {id:'r7',pet:'pet_mochi',type:'allergy',title:'ไก่',date:'2026-07-12',provenance:'Owner entered',reaction:'มีอาการคันตามที่เจ้าของสังเกต',status:'active'},
 {id:'r8',pet:'pet_mochi',type:'vaccine',title:'วัคซีนรวม (ตัวอย่าง)',date:'2025-09-10',provenance:'Owner entered',due:'2026-09-10',reminder:true}
 ],appointments:[{id:'a1',pet:'pet_mochi',title:'ตรวจติดตามประจำปี',clinic:'คลินิกบ้านเพื่อนสัตว์',date:'2026-09-10T10:30',status:'scheduled',reminder:true}],docs:[{id:'d1',pet:'pet_mochi',record:'r6',name:'Mochi_CBC_sample.pdf',size:'240 KB',status:'ready',verified:true}],shares:[],logs:[],adherence:{},targets:{pet_mochi:25},qr:{pet_mochi:{active:false,version:0,fields:['allergy','medication','contact'],contact:'คุณเมย์ · 080-000-0000 (จำลอง)'}},insurance:[],access:[{id:'p1',pet:'pet_mochi',name:'คุณต้น',role:'Co-owner'},{id:'p2',pet:'pet_mochi',name:'คุณพลอย',role:'Viewer'}],preferences:{},verification:{pet_mochi:'verified'},consent:false,shareDraft:null,recipient:null};}
let S=fresh(),toastTimer,modalTrigger;
const pet=()=>petData.find(p=>p.id===S.pet);
function setMobile(view){document.body.dataset.mobile=view;$$('.mobile-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mobile===view));}
const rows=(type)=>S.records.filter(r=>r.pet===S.pet&&!r.deleted&&!r.superseded&&(!type||r.type===type)).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));
const writable=()=>S.role!=='viewer';
const owned=()=>S.role==='owner';
const dateLabel=d=>d?new Date(d.length===10?d+'T12:00:00':d).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'ยังไม่ระบุ';
const today=()=>new Date(S.clock+7*3600000).toISOString().slice(0,10);
const id=prefix=>prefix+(S.next++);
const btn=(label,act,style='primary',disabled=false)=>`<button type="button" class="${style}" data-act="${act}" ${disabled?'disabled':''}>${label}</button>`;
const goBtn=(label,page,style='text-button')=>btn(label,'go:'+page,style);
const notice=(text,warn=false)=>`<div class="notice ${warn?'warn':''}">${text}</div>`;
const badge=r=>`<span class="badge ${r.verified?'green':''}">${r.verified?icon('shield'):''}${esc(r.provenance||'Owner entered')}</span>`;
function log(action,detail){S.logs.unshift({action,detail,at:new Date(S.clock).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})});S.logs=S.logs.slice(0,18);renderDocs();}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function openModal(title,body){modalTrigger=document.activeElement;$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();if(modalTrigger?.isConnected)modalTrigger.focus();}
function guard(owner=false){if(owner?!owned():!writable()){toast('สิทธิ์ปัจจุบันไม่อนุญาตให้ทำรายการนี้');log('DENY role check',{role:S.role,pet_id:S.pet});return false;}return true;}
function go(page){if(!screens.some(s=>s[0]===page))return;S.page=page;S.mode='normal';S.edit=null;S.amend=null;render();$('#app-main').scrollTop=0;$('#app-main').focus({preventScroll:true});}
function startAdd(type){if(!guard())return;S.formType=type;go('add');}
function petContext(){return `<button class="active-pet pet-context" data-act="pets"><span class="avatar">${portrait(pet().kind,0)}</span><span><small>กำลังดูแล · ${S.role==='owner'?'Owner':S.role==='viewer'?'Viewer':'Co-owner'}</small><strong>${pet().name} <span style="font-weight:400">· ${pet().breed}</span></strong></span>${icon('arrow')}</button>`;}
function title(h,p=''){return `<h1>${h}</h1>${p?`<p class="intro">${p}</p>`:''}`;}
function empty(text='ยังไม่มีบันทึก',type='note'){return `<div class="empty">${icon('file')}<h2>${text}</h2><p>เริ่มเก็บเรื่องเล็ก ๆ ของ ${pet().name}<br>แล้วกลับมาติดตามได้ในที่เดียว</p>${writable()?btn('เพิ่มบันทึกแรก','add:'+type):notice('คุณมีสิทธิ์อ่านอย่างเดียว')}</div>`;}
function recordRow(r){return `<button class="record-row" data-act="record:${r.id}"><span class="record-mark">${icon(marks[r.type]||'file')}</span><span><strong>${esc(r.title)}${r.type==='weight'?' · '+r.value+' kg':''}</strong><small>${dateLabel(r.date)} · ${types[r.type]}</small>${badge(r)}</span>${icon('arrow')}</button>`;}
function upcoming(){return [...rows('vaccine').filter(r=>r.due).map(r=>({title:r.title,date:r.due,page:'vaccines',kind:'วัคซีน'})),...S.appointments.filter(a=>a.pet===S.pet&&a.status==='scheduled').map(a=>({title:a.title,date:a.date,page:'appointments',kind:'นัดหมาย'}))].sort((a,b)=>a.date.localeCompare(b.date));}
function home(){const next=upcoming()[0],w=rows('weight')[0],active=S.shares.filter(s=>s.pet===S.pet&&shareState(s)==='active').length;return petContext()+`<span class="eyebrow">EVERYDAY CARE</span><h1 class="care-title">ทุกวันของ ${pet().name}<br>ดูแลได้ในที่เดียว</h1><p class="intro">บันทึกเรื่องสำคัญ แล้วค่อย ๆ ดูแลไปด้วยกัน</p>`+(next?`<section class="next-action"><span class="decor-line" aria-hidden="true">⌁</span><span class="eyebrow">สิ่งที่ต้องทำถัดไป · ${next.kind}</span><h2>${esc(next.title)}</h2><p>${dateLabel(next.date)} · ${next.date.slice(0,10)<today()?'เลยกำหนดที่บันทึกไว้':'กำหนดการที่คุณบันทึกไว้'}</p>${goBtn('ดูรายละเอียด '+icon('arrow'),next.page,'primary')}</section>`:notice('ยังไม่มีกำหนดการถัดไป เพิ่มวัคซีนหรือนัดหมายได้เมื่อพร้อม'))+`<div class="quick-grid">${[['น้ำหนัก','weight','tune'],['ให้ยา','meds','heart'],['นัดหมาย','appointments','pin'],['บันทึก','add','plus']].map(([t,p,i])=>`<button data-act="${p==='weight'?'add:weight':'go:'+p}">${icon(i)}${t}</button>`).join('')}</div><div class="section-heading"><h2>ล่าสุดของเรา</h2>${goBtn('ดูทั้งหมด','timeline')}</div>${rows().slice(0,2).map(recordRow).join('')||empty()}<div class="fact-pair"><div><small>น้ำหนักล่าสุด</small><strong>${w?w.value+' <small>kg</small>':'—'}</strong><small>${w?dateLabel(w.date):'ยังไม่มีข้อมูล'}</small></div><div><small>การแชร์ที่ยังใช้งาน</small><strong>${active} <small>รายการ</small></strong>${goBtn('จัดการสิทธิ์','shares')}</div></div>${goBtn(icon('shield')+' Emergency Card','emergency','secondary full')}`;}
function timeline(){const f=S.filter;let rr=rows().filter(r=>(f.type==='all'||r.type===f.type)&&(f.provenance==='all'||(f.provenance==='verified'?r.verified:!r.verified))&&(!f.from||r.date>=f.from)&&(!f.to||r.date<=f.to));return petContext()+title('ประวัติสุขภาพ','ทุกบันทึกมีที่มา ย้อนกลับมาดูได้เสมอ')+`<div class="filter-grid"><label>ประเภท<select id="filter-type"><option value="all">ทุกประเภท</option>${Object.entries(types).map(([k,v])=>`<option value="${k}" ${f.type===k?'selected':''}>${v}</option>`).join('')}</select></label><label>แหล่งข้อมูล<select id="filter-provenance"><option value="all">ทุกแหล่ง</option><option value="owner" ${f.provenance==='owner'?'selected':''}>Owner entered</option><option value="verified" ${f.provenance==='verified'?'selected':''}>Vet verified</option></select></label><label>ตั้งแต่<input type="date" id="filter-from" value="${f.from}"></label><label>ถึง<input type="date" id="filter-to" value="${f.to}"></label></div><div class="actions">${btn('+ เพิ่มบันทึก','add:note','primary',!writable())}${btn('ล้างตัวกรอง','clear-filter','secondary')}</div>${rr.map(recordRow).join('')||empty('ไม่พบบันทึกตามตัวกรอง')}`;}
const field=(label,name,type='text',value='',required=false,attrs='')=>`<label for="f-${name}">${label}${required?' *':''}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${attrs}>`;
const selectField=(label,name,options,value)=>`<label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options.map(([k,v])=>`<option value="${k}" ${value===k?'selected':''}>${v}</option>`).join('')}</select>`;
function recordForm(){if(!writable())return petContext()+title('เพิ่มบันทึก')+notice('Viewer อ่านได้ แต่เพิ่มหรือแก้ไขประวัติไม่ได้',true);const r=S.records.find(r=>r.id===S.edit)||S.records.find(r=>r.id===S.amend)||{},t=S.formType;let fields='';
 if(t==='vaccine')fields=selectField('ช่วยเลือกชื่อวัคซีน','preset',[['custom','กรอกเอง'],['พิษสุนัขบ้า','พิษสุนัขบ้า'],[pet().kind==='dog'?'วัคซีนรวมสุนัข':'วัคซีนรวมแมว',pet().kind==='dog'?'วัคซีนรวมสุนัข':'วัคซีนรวมแมว']],'custom')+field('ชื่อวัคซีน','title','text',r.title||'',true)+field('วันที่ฉีด','date','date',r.date||today(),true)+field('กำหนดครั้งถัดไป (ไม่บังคับ)','due','date',r.due||'')+field('คลินิก / ผู้ให้บริการ','provider','text',r.provider||'')+notice('รายการช่วยกรอกเท่านั้น กำหนดครั้งถัดไปให้ใช้วันที่ที่คุณหรือสัตวแพทย์ระบุ');
 else if(t==='weight')fields=field('น้ำหนัก (kg)','value','number',r.value||'',true,'min="0.01" max="1000" step="0.01"')+field('วันที่ชั่ง','date','date',r.date||today(),true)+notice('BCS และ rapid-change threshold ยังรอนโยบาย จึงไม่ใส่ค่าเริ่มต้นหรือสรุปสุขภาพในเดโม');
 else if(t==='medication')fields=field('ชื่อยาตามที่บันทึก','title','text',r.title||'',true)+`<div class="inline-field"><div>${field('ปริมาณต่อครั้ง','dose','number',r.dose||'',true,'min="0.001" step="any"')}</div><div>${field('หน่วย','unit','text',r.unit||'',true)}</div></div>`+field('ความถี่ / เวลาที่ให้','frequency','text',r.frequency||'',true)+field('วันที่เริ่ม','date','date',r.date||today(),true)+field('วันที่สิ้นสุด','end','date',r.end||'',true)+notice('เดโมแสดงตารางที่คุณกรอก ไม่คำนวณขนาดยาหรือแนะนำวิธีรักษา');
 else if(t==='lab')fields=field('ชื่อชุดตรวจ','title','text',r.title||'',true)+field('วันที่ตรวจ','date','date',r.date||today(),true)+field('ชื่อรายการตรวจ','test','text',r.test||'',true)+selectField('ชนิดผลตรวจ','resultKind',[['numeric','ตัวเลข'],['text','ข้อความ']],'numeric')+field('ผลตรวจ','result','text',r.result??'',true)+field('หน่วย (ถ้ามี)','unit','text',r.unit||'')+`<div class="inline-field"><div>${field('ค่าต่ำสุดจากรายงาน','low','number',r.low??'',false,'step="any"')}</div><div>${field('ค่าสูงสุดจากรายงาน','high','number',r.high??'',false,'step="any"')}</div></div>`+notice('กรอกช่วงอ้างอิงจากรายงานเท่านั้น หากไม่มีจะไม่แสดงสถานะปกติ/ผิดปกติ');
 else fields=field(t==='allergy'?'สิ่งที่แพ้':t==='diagnosis'?'การวินิจฉัยที่ได้รับ':'หัวข้อบันทึก','title','text',r.title||'',true)+field('วันที่','date','date',r.date||today(),true)+(t==='allergy'?field('อาการที่สังเกต','reaction','text',r.reaction||'',true):'');
 return petContext()+title(S.edit?'แก้ไขบันทึก':S.amend?'สร้าง amendment':'เพิ่มบันทึกสุขภาพ',S.amend?'ต้นฉบับที่ยืนยันแล้วจะคงเดิม · ฉบับใหม่ยังไม่ผ่านการยืนยัน':'บันทึกเท่าที่ทราบ เพิ่มรายละเอียดภายหลังได้')+(!S.edit&&!S.amend?`<label for="record-type">ชนิดบันทึก</label><select id="record-type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${t===k?'selected':''}>${v}</option>`).join('')}</select>`:'')+`<form id="record-form">${fields}<label for="f-notes">หมายเหตุ</label><textarea id="f-notes" name="notes">${esc(r.notes||'')}</textarea>${['vaccine','medication'].includes(t)?'<label class="check-label"><input type="checkbox" name="reminder" '+(r.reminder!==false?'checked':'')+'> เปิดการแจ้งเตือนตามวันที่บันทึก</label>':''}<p class="field-note">ไฟล์แนบเพิ่มได้จากหน้าเอกสารหลังบันทึก · * ช่องจำเป็น</p><button class="primary full" type="submit">${S.amend?'บันทึกฉบับแก้ไข':'บันทึกข้อมูล'}</button></form>`;
}
function vaccines(){return petContext()+title('วัคซีน','ดูวันที่ฉีดและกำหนดครั้งถัดไปของแต่ละรายการ')+btn('+ เพิ่มวัคซีน','add:vaccine','primary full',!writable())+ (rows('vaccine').map(r=>`<div class="card-panel"><div class="row"><h3>${esc(r.title)}</h3>${icon('shield')}</div>${badge(r)}<p>ฉีดเมื่อ ${dateLabel(r.date)}</p><div class="inline-status">ครั้งถัดไป ${r.due?dateLabel(r.due):'ยังไม่กำหนด'}${r.due&&r.due<today()?' · เลยกำหนด':''}</div><div class="actions">${btn('ดูประวัติ','record:'+r.id,'secondary')}${btn(r.reminder?'ปิดเตือน':'เปิดเตือน','remind:'+r.id,'outline',!writable())}</div></div>`).join('')||empty('ยังไม่มีประวัติวัคซีน','vaccine'));}
function meds(){return petContext()+title('ยา & การให้ยา','ทำตามตารางที่บันทึก โดยไม่พลาดรายการของวันนี้')+btn('+ เพิ่มรายการยา','add:medication','primary full',!writable())+(rows('medication').map(r=>{const status=S.adherence[r.id+today()];return `<div class="card-panel"><div class="row"><h3>${esc(r.title)}</h3><span class="badge">${r.status==='active'?'กำลังใช้งาน':r.status==='stopped'?'หยุดแล้ว':'ครบกำหนด'}</span></div><p>${esc(r.dose)} ${esc(r.unit)} · ${esc(r.frequency)}</p><p>${dateLabel(r.date)} – ${dateLabel(r.end)}</p>${r.status==='active'?`<div class="inline-status">${dateLabel(today())} · ${status==='taken'?'บันทึกว่าให้แล้ว':status==='skipped'?'บันทึกว่าข้ามแล้ว':'ยังไม่ได้บันทึกการให้ยา'}</div><div class="actions">${btn('ให้แล้ว','dose:'+r.id+':taken','primary',!writable()||!!status)}${btn('ข้ามครั้งนี้','dose:'+r.id+':skipped','secondary',!writable()||!!status)}</div><div class="actions">${btn('จบรายการ','med-complete:'+r.id,'outline',!writable())}${btn('หยุดก่อนกำหนด','med-stop:'+r.id,'outline',!writable())}</div>`:''}${btn('ดูรายละเอียด','record:'+r.id,'text-button')}</div>`;}).join('')||empty('ยังไม่มีรายการยา','medication'))+notice('บันทึก “ให้แล้ว” ไม่ใช่คำสั่งให้ยา · หนึ่ง slot ต่อวันในเดโม ไม่ได้ส่ง notification จริง');}
function appointments(){return petContext()+title('นัดหมาย','ดูแลเรื่องนัด แล้วเก็บสิ่งที่เกิดขึ้นหลังพบคุณหมอ')+btn('+ สร้างนัดหมาย','new-appointment','primary full',!writable())+(S.appointments.filter(a=>a.pet===S.pet).map(a=>`<div class="card-panel"><span class="badge">${({scheduled:'รอถึงวันนัด',completed:'เสร็จสิ้น',cancelled:'ยกเลิก',no_show:'ไม่ได้ไปตามนัด'})[a.status]}</span><h3>${esc(a.title)}</h3><p>${dateLabel(a.date)} · ${a.date.slice(11,16)} น.</p><p>${esc(a.clinic)}</p>${a.status==='scheduled'?`<div class="actions">${btn('เสร็จสิ้น','appointment:'+a.id+':completed','primary',!writable())}${btn('เลื่อนนัด','reschedule:'+a.id,'secondary',!writable())}</div><div class="actions">${btn('ยกเลิกนัด','appointment:'+a.id+':cancelled','outline',!writable())}${btn('ไม่ได้ไป','appointment:'+a.id+':no_show','outline',!writable())}</div>`:a.status==='completed'?a.linked?btn('ดูบันทึกที่เชื่อมแล้ว','record:'+a.linked,'secondary full'):btn('สร้างบันทึกจากนัดนี้','convert:'+a.id,'secondary full',!writable()):''}</div>`).join('')||notice('ยังไม่มีนัดหมาย ลองเพิ่มรายการแรก'))}
function weight(){const wr=rows('weight').slice().reverse(),last=wr.at(-1),prev=wr.at(-2),pct=prev?((last.value-prev.value)/prev.value*100).toFixed(1):null;let chart='';if(wr.length){const min=Math.min(...wr.map(r=>r.value))-.3,max=Math.max(...wr.map(r=>r.value))+.3,pts=wr.map((r,i)=>[wr.length===1?170:30+i*280/(wr.length-1),140-(r.value-min)/(max-min)*100]);chart=`<svg viewBox="0 0 340 190" class="weight-chart" role="img" aria-label="แนวโน้มน้ำหนัก ${wr.map(r=>r.value+' กิโลกรัม').join(', ')}"><path d="M25 145H320M25 95H320M25 45H320" stroke="#d9e1d2" stroke-dasharray="3 5"/><polyline points="${pts.map(p=>p.join(',')).join(' ')}"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5"/><text x="${p[0]}" y="${p[1]-13}" text-anchor="middle">${wr[i].value}</text>`).join('')}<text x="25" y="177">${dateLabel(wr[0].date)}</text><text x="315" y="177" text-anchor="end">${dateLabel(last.date)}</text></svg>`;}return petContext()+title('เติบโตไปด้วยกัน','น้ำหนักตามวันที่วัด · ไม่ใช่คะแนนสุขภาพ')+`<div class="fact-pair"><div><small>ล่าสุด</small><strong>${last?last.value:'—'} <small>kg</small></strong><small>${last?dateLabel(last.date):'ยังไม่บันทึก'}</small></div><div><small>เทียบครั้งก่อน</small><strong>${pct!==null?(+pct>0?'+':'')+pct+'%':'—'}</strong><small>${prev?'จาก '+prev.value+' kg':'ต้องมีอย่างน้อย 2 ครั้ง'}</small></div></div>${btn('+ บันทึกน้ำหนัก','add:weight','primary full',!writable())}${chart}<details><summary>ดูข้อมูลเป็นตาราง</summary><table><thead><tr><th>วันที่วัด</th><th>น้ำหนัก (kg)</th></tr></thead><tbody>${wr.map(r=>`<tr><td>${dateLabel(r.date)}</td><td>${r.value}</td></tr>`).join('')}</tbody></table></details><div class="card-panel"><div class="row"><span>น้ำหนักเป้าหมาย</span><strong>${S.targets[S.pet]||'—'} kg</strong></div>${btn('แก้เป้าหมายที่บันทึก','target','text-button',!writable())}</div>${notice('BCS / rapid-change alert รอนโยบายก่อนใช้งานจริง เดโมไม่ตีความว่ามีน้ำหนักเหมาะสมหรือไม่')}`;}
function range(r){if(r.resultKind==='text'||typeof r.result!=='number'||(r.low==null&&r.high==null))return 'ไม่มีช่วงอ้างอิงที่ใช้เปรียบเทียบ';if(r.low!=null&&r.result<r.low)return '↓ Low · นอกช่วงอ้างอิง';if(r.high!=null&&r.result>r.high)return '↑ High · นอกช่วงอ้างอิง';return 'อยู่ในช่วงอ้างอิงที่ระบุ';}
function labs(){return petContext()+title('ผลแล็บ','เก็บผลจากรายงาน พร้อมแหล่งที่มา')+btn('+ เพิ่มผลตรวจ','add:lab','primary full',!writable())+(rows('lab').map(r=>`<div class="card-panel"><h3>${esc(r.title)}</h3>${badge(r)}<p>${dateLabel(r.date)}</p><table><thead><tr><th>รายการ</th><th>ผล / หน่วย</th></tr></thead><tbody><tr class="${range(r).includes('นอกช่วง')?'out-range':''}"><td>${esc(r.test)}</td><td class="mono lab-value">${esc(r.result)}<br><small>${esc(r.unit)}</small></td></tr><tr><td>ช่วงจากรายงาน</td><td class="mono">${r.low??'—'} – ${r.high??'—'}</td></tr></tbody></table><div class="inline-status">${esc(range(r))}</div>${btn('รายละเอียด & เอกสาร','record:'+r.id,'text-button')}</div>`).join('')||empty('ยังไม่มีผลแล็บ','lab'))+notice('ค่าตัวอย่างในเดโมไม่ใช่เกณฑ์ทางการแพทย์ ไม่มีการแปลผลหรือตัดสินสุขภาพ');}
function allergies(){return petContext()+title('แพ้ & การวินิจฉัย','แยกบันทึกที่เจ้าของกรอกกับข้อมูลที่ยืนยันแล้ว')+`<div class="actions">${btn('+ การแพ้','add:allergy','primary',!writable())}${btn('+ การวินิจฉัย','add:diagnosis','secondary',!writable())}</div>`+(rows().filter(r=>['allergy','diagnosis'].includes(r.type)).map(r=>`<div class="card-panel"><span class="badge">${types[r.type]} · ${r.status==='resolved'?'ไม่ใช้งานแล้ว':'ใช้งาน'}</span><h3>${esc(r.title)}</h3><p>${esc(r.reaction||r.notes)}</p>${badge(r)}<div class="actions">${btn('ดูรายละเอียด','record:'+r.id,'secondary')}${btn(r.verified?'สร้าง amendment':r.status==='resolved'?'ตั้งเป็นใช้งาน':'ตั้งเป็นไม่ใช้งาน',r.verified?'amend:'+r.id:'resolve:'+r.id,'outline',!writable())}</div></div>`).join('')||empty('ยังไม่มีรายการแพ้หรือการวินิจฉัย','allergy'));}
function documents(){return petContext()+title('เอกสารสุขภาพ','เป็นส่วนตัวเสมอ แชร์เฉพาะเมื่อคุณเลือก')+`<form id="upload-form" class="card-panel"><label for="doc-record">เชื่อมกับบันทึก</label><select id="doc-record" name="record" required><option value="">เลือกบันทึก</option>${rows().map(r=>`<option value="${r.id}">${esc(r.title)}</option>`).join('')}</select><label for="doc-file">PDF / JPG / PNG</label><input class="file-select" type="file" id="doc-file" accept=".pdf,.jpg,.jpeg,.png" name="file" required ${!writable()?'disabled':''}><p class="field-note">ขนาดสูงสุด 10 MB สำหรับเดโม · เก็บเฉพาะชื่อไฟล์ ไม่มี upload หรือ malware scan จริง</p><button class="primary full" ${!writable()?'disabled':''}>แนบเอกสารจำลอง</button></form>`+S.docs.filter(d=>d.pet===S.pet).map(d=>`<div class="card-panel doc-list"><div class="row"><span class="file-icon">${d.name.split('.').pop().toUpperCase()}</span><strong style="font-size:11px;overflow-wrap:anywhere">${esc(d.name)}</strong></div><p>${esc(d.size)} · ${d.status==='ready'?'พร้อมดูตัวอย่าง':d.status==='scanning'?'รอจำลองผลตรวจ':'ปฏิเสธไฟล์'}</p><div class="actions">${d.status==='scanning'?btn('จำลองตรวจผ่าน','scan:'+d.id+':ready','secondary',!writable())+btn('จำลองปฏิเสธ','scan:'+d.id+':rejected','outline',!writable()):btn('ดูรายละเอียด','document:'+d.id,'secondary',d.status!=='ready')}${btn('ลบ','delete-doc:'+d.id,'outline',!writable())}</div></div>`).join('');}
function shareState(s){return s.status==='revoked'?'revoked':s.expires<=S.clock?'expired':'active';}
function share(){if(!owned())return petContext()+title('แชร์ข้อมูลสุขภาพ')+notice('Owner เท่านั้นที่จัดการ share ในเดโมนี้ · Co-owner รอ explicit grant policy',true);return petContext()+title('แชร์เท่าที่จำเป็น','เลือกข้อมูลให้ชัด ก่อนส่งให้คนที่คุณไว้ใจ')+`<form id="share-form">${field('ผู้รับ (อีเมลจำลอง)','recipient','email','vet@example.test',true)}<label>เลือกบันทึกที่ผู้รับอ่านได้</label><p class="field-note">Snapshot เฉพาะรายการที่เลือก ไม่รวมข้อมูลใหม่ในอนาคต</p>${rows().filter(r=>r.type!=='weight').map(r=>`<label class="check-label"><input name="records" type="checkbox" value="${r.id}"><span>${esc(r.title)}<br><small>${types[r.type]} · ${dateLabel(r.date)}</small></span></label>`).join('')}${S.docs.filter(d=>d.pet===S.pet&&d.status==='ready').length?'<label>เอกสาร (ไม่รวมโดยอัตโนมัติ)</label>':''}${S.docs.filter(d=>d.pet===S.pet&&d.status==='ready').map(d=>`<label class="check-label"><input type="checkbox" name="documents" value="${d.id}">${esc(d.name)}</label>`).join('')}${field('หมดอายุวันที่','expiry','date',new Date(S.clock+7*86400000).toISOString().slice(0,10),true,'min="'+today()+'"')}<button class="primary full">ตรวจสอบก่อนแชร์ ${icon('arrow')}</button></form>`;}
function shares(){if(!owned())return petContext()+title('สิทธิ์ที่แชร์อยู่')+notice('หน้านี้สำหรับ Owner จัดการสิทธิ์ของผู้รับ',true);return petContext()+title('สิทธิ์ที่แชร์อยู่','เห็นชัดว่าใครเข้าถึงอะไร และหยุดได้เมื่อคุณต้องการ')+goBtn('+ แชร์ข้อมูล','share','primary full')+(S.shares.filter(s=>s.pet===S.pet).map(s=>`<div class="card-panel"><span class="badge ${shareState(s)==='active'?'green':'warn'}">${({active:'ใช้งาน',expired:'หมดอายุ',revoked:'ถอนสิทธิ์แล้ว'})[shareState(s)]}</span><h3>${esc(s.recipient)}</h3><p>${s.records.length} บันทึก · ${s.documents.length} เอกสาร</p><p>หมดอายุ ${dateLabel(new Date(s.expires).toISOString())}</p><div class="actions">${btn('ลองมุมมองผู้รับ','recipient:'+s.id,'secondary')}${btn('ถอนสิทธิ์','revoke:'+s.id,'outline',!owned()||shareState(s)!=='active')}</div></div>`).join('')||notice('ยังไม่ได้แชร์ข้อมูลกับใคร'))+`<div class="policy-note">ทดลอง expiry โดยเลื่อนเวลาเดโม ไม่เปลี่ยนนาฬิกาจริง${btn('จำลองเวลา +8 วัน','advance','text-button')}</div>`;}
function verification(){const v=S.verification[S.pet];return petContext()+title('ศูนย์การยืนยัน','แยกประเภทการยืนยันอย่างชัดเจน')+notice('แนวทาง Phase 2 · release scope รอตัดสินใจ (DEC-01) ปุ่มทั้งหมดจำลองการตัดสิน ไม่ใช่ Vet จริง',true)+[['Vaccine Verified',v==='verified'?'ยืนยันแล้ว · ข้อมูลจำลอง':v==='pending'?'รอตรวจสอบ':v==='expired'?'หมดอายุ':'ยังไม่ยืนยัน'],['Health Screening Verified','ยังไม่มีหลักฐาน'],['Breeding Health Verified','ยังไม่มีหลักฐาน']].map(([t,s])=>`<div class="card-panel"><h3>${t}</h3><p>${s}</p></div>`).join('')+`<div class="actions">${btn('จำลองขอยืนยัน','verify:pending','primary',!owned())}${btn('จำลอง Vet ยืนยัน','verify:verified','secondary',!owned()||v!=='pending')}</div>${btn('จำลองหมดอายุ','verify:expired','outline full',!owned()||v!=='verified')}${notice('Matching รับเฉพาะ safe summary · Breeding ยังไม่ผ่าน เพราะ screening / policy requirements ยังไม่ครบ')}<div class="card-panel"><h3>AI OCR / extraction</h3><p>Phase 2 · ตัวอย่างการตรวจ field ก่อนบันทึก ไม่เรียก AI จริง</p>${btn('ทดลอง review ข้อมูล','ai-review','secondary full',!writable())}</div>`;}
function qrConfig(){return S.qr[S.pet]||{active:false,version:0,fields:[],contact:''};}
function emergency(){const q=qrConfig();return petContext()+title('เผื่อวันที่ต้องรีบ','ข้อมูลฉุกเฉินที่คุณเลือกให้คนช่วยเหลืออ่านได้')+`<div class="qr-preview"><div><strong>Emergency<br>Card</strong><br><small>${q.active?'Token #'+q.version+' · ใช้งาน':'ยังไม่เปิดใช้งาน'}<br>จำลอง QR ไม่ใช่รหัสสแกนจริง</small></div></div><form id="qr-form"><label>เลือกข้อมูลบนบัตร</label>${[['allergy','ข้อมูลแพ้ที่ใช้งาน'],['medication','ยาที่ใช้อยู่'],['contact','ผู้ติดต่อฉุกเฉิน']].map(([v,l])=>`<label class="check-label"><input type="checkbox" name="fields" value="${v}" ${q.fields.includes(v)?'checked':''} ${!owned()?'disabled':''}>${l}</label>`).join('')}${field('ผู้ติดต่อและเบอร์โทร (ใช้ข้อมูลจำลอง)','contact','text',q.contact)}<button class="primary full" ${!owned()?'disabled':''}>${q.active?'บันทึกขอบเขตบัตร':'เปิดใช้งานบัตรจำลอง'}</button></form><div class="actions">${btn('ลองสแกนบัตร','qr-view:'+q.version,'secondary',!q.active)}${btn('หมุน token ใหม่','qr-rotate','outline',!owned()||!q.active)}</div>${btn('ปิดบัตร / ถอนสิทธิ์','qr-revoke','outline full',!owned()||!q.active)}${q.version>1?btn('ทดลองเปิด token เก่า','qr-view:'+(q.version-1),'text-button full'):''}${notice('บัตรจำกัดเฉพาะช่องที่เลือก ไม่เปิดผลแล็บ เอกสารหรือเลขกรมธรรม์ และไม่ต้องเข้าสู่ระบบใน flow จริง')}`;}
function insurance(){return petContext()+title('ประกันของเพื่อนรัก','รายละเอียดกรมธรรม์และวันสิ้นสุดความคุ้มครอง')+btn('+ เพิ่มกรมธรรม์','new-insurance','primary full',!writable())+(S.insurance.filter(p=>p.pet===S.pet).map(p=>`<div class="card-panel"><h3>${esc(p.provider)}</h3><p>เลขกรมธรรม์ ••••${esc(p.number.slice(-4))}</p><p>${esc(p.coverage)}</p><span class="badge ${p.expiry<today()?'warn':'green'}">${p.expiry<today()?'หมดอายุ':'ใช้งาน'} · ถึง ${dateLabel(p.expiry)}</span><div class="actions">${btn(p.reminder?'ปิดเตือนหมดอายุ':'เปิดเตือนหมดอายุ','policy-reminder:'+p.id,'outline',!writable())}</div></div>`).join('')||notice('ยังไม่มีกรมธรรม์ ลองเพิ่มข้อมูลตัวอย่าง'))+notice('เลขกรมธรรม์ไม่แสดงบน Emergency Card');}
function nutrition(){const context=S.nutrition?.[S.pet]||{};return petContext()+title('โภชนาการ','เก็บบริบทให้พร้อมสำหรับการประเมิน')+`<form id="nutrition-form">${field('น้ำหนักเป้าหมาย (kg)','target','number',S.targets[S.pet]||'',true,'min="0.01" step="0.01"')}${selectField('ช่วงวัย','stage',[['adult','โตเต็มวัย'],['young','วัยเด็ก'],['senior','สูงวัย']],context.stage||'adult')}${selectField('สถานะทำหมัน','neutered',[['yes','ทำหมันแล้ว'],['no','ยังไม่ทำหมัน'],['unknown','ไม่ทราบ']],context.neutered||'yes')}<button class="primary full" ${!writable()?'disabled':''}>บันทึกบริบท</button></form>${notice('ยังไม่คำนวณพลังงาน: สูตรและ policy version ยังรออนุมัติ (DEC-12) เดโมไม่แสดงตัวเลขแคลอรีที่ไม่มีที่มา',true)}`;}
function access(){return petContext()+title('คนที่ช่วยกันดูแล','สิทธิ์ผูกกับสัตว์เลี้ยงแต่ละตัว')+`<div class="card-panel"><h3>คุณเมย์ <span class="badge green">Owner</span></h3><p>เจ้าของหลักของ ${pet().name}</p></div>`+S.access.filter(p=>p.pet===S.pet).map(p=>`<div class="card-panel"><h3>${esc(p.name)} <span class="badge">${p.role}</span></h3><p>${p.role==='Viewer'?'อ่านอย่างเดียว · แก้ไขหรือแชร์ต่อไม่ได้':'เพิ่มและแก้ owner-entered records · แชร์ไม่ได้ในเดโม'}</p>${btn('ถอนสิทธิ์','remove-access:'+p.id,'text-button',!owned())}</div>`).join('')+btn('+ เชิญผู้ช่วยดูแล','invite','primary full',!owned())+notice('ตัวสลับบทบาทด้านขวาใช้ทดสอบ UI เท่านั้น ระบบจริงต้องตรวจสิทธิ์ฝั่ง server ทุกครั้ง');}
function notifications(){const prefs=S.preferences[S.pet]||{};return petContext()+title('แจ้งเตือนในแบบของคุณ','เลือกเรื่องที่อยากให้ช่วยเตือน')+`<form id="notify-form">${['วัคซีน','ยา','นัดหมาย','บันทึกน้ำหนัก','ตรวจประจำปี','ตรวจสุขภาพ','ป้องกันปรสิต','ประกันหมดอายุ'].map((n,i)=>`<label class="check-label"><input name="n${i}" type="checkbox" ${prefs['n'+i]!==false?'checked':''} ${!writable()?'disabled':''}>${n}</label>`).join('')}${selectField('เตือนก่อนกำหนด','offset',[['1','1 วัน'],['3','3 วัน'],['7','7 วัน']],prefs.offset||'1')}${notice('ช่องทางเดโม: ในแอป · ไม่มี push/email จริง · ตารางยารายวันใช้เวลาที่เจ้าของบันทึก')}<button class="primary full" ${!writable()?'disabled':''}>บันทึกการแจ้งเตือน</button></form>`;}
const pageFns={home,timeline,add:recordForm,vaccines,meds,appointments,weight,labs,allergies,documents,share,shares,verification,emergency,insurance,nutrition,access,notifications};
function render(){const screen=screens.find(s=>s[0]===S.page);$('#screen-menu').innerHTML=screens.map((s,i)=>`${s[2]?`<div class="screen-group">${s[2]}</div>`:''}<button class="screen-link ${S.page===s[0]?'active':''}" data-act="go:${s[0]}" ${S.page===s[0]?'aria-current="page"':''}><span class="num">${String(i+1).padStart(2,'0')}</span>${s[1]}</button>`).join('');$('#screen-position').textContent='HC-'+String(screens.indexOf(screen)+1).padStart(2,'0');$('#appbar').innerHTML=`<div class="brand">PawVerse<span style="font:10px system-ui;margin-left:5px;color:var(--muted)">HEALTH</span></div><button class="round" aria-label="ตั้งค่าการแจ้งเตือน" data-act="go:notifications">${icon('bell')}</button>`;$('#bottom-nav').innerHTML=[['home','heart','หน้าหลัก'],['timeline','file','ประวัติ'],['weight','tune','ติดตาม'],['documents','file','เอกสาร'],['shares','shield','การแชร์']].map(([p,i,l])=>`<button class="nav-btn ${S.page===p?'active':''}" data-act="${p==='weight'?'trackers':'go:'+p}">${icon(i)}${l}</button>`).join('');let content;
if(S.mode==='loading')content=petContext()+title('กำลังโหลดข้อมูล')+'<div role="status" aria-label="กำลังโหลด"><div class="skeleton short"></div><div class="skeleton"></div><div class="skeleton"></div></div>'+btn('จำลองโหลดสำเร็จ','recover','secondary full');else if(S.mode==='error')content=petContext()+title('โหลดข้อมูลไม่สำเร็จ')+notice('ลองใหม่อีกครั้ง ข้อมูลที่บันทึกไว้ยังอยู่',true)+btn('ลองใหม่','recover','primary full');else if(S.mode==='denied')content=title('ไม่มีสิทธิ์เข้าถึง')+notice('ข้อมูลหน้านี้ไม่อยู่ในสิทธิ์ที่ได้รับ',true)+btn('กลับสู่เดโม','recover','primary full');else if(S.mode==='empty')content=petContext()+title(screen[1])+empty('ยังไม่มีข้อมูลในหน้านี้')+btn('กลับข้อมูลตัวอย่าง','recover','secondary full');else content=pageFns[S.page]();$('#app-main').innerHTML=content;$('#demo-role').value=S.role;$('#demo-state').value=S.mode;renderDocs();}
function detail(rid){const r=S.records.find(r=>r.id===rid&&r.pet===S.pet&&!r.deleted);if(!r)return toast('ไม่พบบันทึกหรือไม่มีสิทธิ์');const docs=S.docs.filter(d=>d.record===r.id),fields=[['ประเภท',types[r.type]],['วันที่',dateLabel(r.date)],['แหล่งข้อมูล',r.provenance],['สถานะ',r.superseded?'ฉบับก่อนหน้า':r.verified?'Verified · ต้นฉบับแก้ไม่ได้':'ยังไม่ผ่านการยืนยัน'],['การแชร์',S.shares.filter(s=>shareState(s)==='active'&&s.records.includes(r.id)).length+' ผู้รับ'],...(r.value?[['น้ำหนัก',r.value+' kg']]:[]),...(r.parent?[['ฉบับต้นทาง',r.parent]]:[])];openModal(r.title,`${badge(r)}<dl class="detail-grid">${fields.map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p>${esc(r.notes||r.reaction||'ไม่มีหมายเหตุเพิ่มเติม')}</p>${docs.map(d=>btn('เอกสาร: '+esc(d.name),'document:'+d.id,'text-button',d.status!=='ready')).join('')}${r.superseded?notice('ฉบับนี้เป็นประวัติก่อน amendment และเก็บไว้ตรวจสอบย้อนหลัง'): `<div class="actions">${btn(r.verified?'สร้าง amendment':'แก้ไข',r.verified?'amend:'+r.id:'edit:'+r.id,'primary',!writable())}${btn('ลบบันทึก','delete:'+r.id,'outline',!writable()||!!r.verified)}</div>`}${r.parent?btn('ดูต้นฉบับก่อนหน้า','record:'+r.parent,'secondary full'):''}`);log('GET /health/records/{id}',{record_id:r.id,pet_id:S.pet,authorized:true});}
function recipientView(sid){const s=S.shares.find(s=>s.id===sid&&s.pet===S.pet);if(!s)return;S.recipient=sid;const status=shareState(s);if(status!=='active'){openModal('เข้าถึงข้อมูลไม่ได้',notice(status==='revoked'?'สิทธิ์นี้ถูกถอนแล้ว · ไม่มีข้อมูลแสดง':'สิทธิ์นี้หมดอายุแล้ว · ไม่มีข้อมูลแสดง',true)+btn('ปิด','close','primary full'));log('DENY GET /shares/{token}',{grant_id:s.id,status});return;}openModal('มุมมองผู้รับ',`<span class="badge">Read-only · ${esc(s.recipient)}</span><p>ข้อมูลของ ${petData.find(p=>p.id===s.pet).name} ที่ Owner เลือกให้คุณ</p>${s.records.map(rid=>S.records.find(r=>r.id===rid&&!r.deleted)).filter(Boolean).map(r=>`<div class="card-panel"><h3>${esc(r.title)}</h3><p>${types[r.type]} · ${dateLabel(r.date)}</p>${badge(r)}</div>`).join('')}${s.documents.map(did=>{const d=S.docs.find(d=>d.id===did);return d?btn('เปิด '+esc(d.name),'shared-doc:'+s.id+':'+d.id,'text-button'):''}).join('')}${notice('ไม่รวมข้อมูลใหม่หรือเอกสารที่ไม่ได้เลือก · แชร์สิทธิ์ต่อไม่ได้')}<div class="actions">${btn('จำลอง Owner ถอนสิทธิ์','revoke-live:'+s.id,'outline',!owned())}${btn('โหลดอีกครั้ง','recipient:'+s.id,'secondary')}</div>`);log('GET /shares/{token}',{grant_id:s.id,record_count:s.records.length,document_count:s.documents.length,scope_checked:true});}
function qrView(version){const q=qrConfig();if(!q.active||Number(version)!==q.version){openModal('บัตรนี้ใช้ไม่ได้แล้ว',notice('Token ถูกเปลี่ยนหรือถอนสิทธิ์ ไม่มีข้อมูลสุขภาพแสดง',true));log('DENY emergency token',{version});return;}openModal('Emergency · '+pet().name,`<span class="badge">Limited public view · ตัวอย่าง</span>${q.fields.includes('allergy')?'<h3>ข้อมูลแพ้</h3>'+rows('allergy').filter(r=>r.status!=='resolved').map(r=>'<p>'+esc(r.title)+'</p>').join(''):''}${q.fields.includes('medication')?'<h3>ยาที่ใช้อยู่</h3>'+rows('medication').filter(r=>r.status==='active').map(r=>'<p>'+esc(r.title)+' · '+esc(r.dose)+' '+esc(r.unit)+'</p>').join(''):''}${q.fields.includes('contact')?'<h3>ผู้ติดต่อฉุกเฉิน</h3><p>'+esc(q.contact)+'</p>':''}${notice('แสดงเฉพาะช่องที่ Owner เลือก · ไม่มีเอกสารหรือผลแล็บ')}${btn('ปิด','close','primary full')}`);log('GET emergency limited view',{pet_id:S.pet,fields:q.fields,version:q.version});}
function actions(action){const [key,arg,arg2]=action.split(':');let r=S.records.find(r=>r.id===arg&&r.pet===S.pet);if(key==='go'){go(arg);setMobile('app');return;}if(key==='close'){closeModal();return;}if(key==='record'){detail(arg);return;}if(key==='add'){startAdd(arg);return;}if(key==='recover'){S.mode='normal';render();return;}
switch(key){
case'reset':closeModal();S=fresh();render();toast('คืนค่าข้อมูลจำลองทั้งหมดแล้ว');break;
case'pets':openModal('เลือกเพื่อนที่กำลังดูแล',petData.map((p,i)=>`<button class="list-item" data-act="pet:${p.id}"><span class="avatar">${portrait(p.kind,i)}</span><span class="fill"><strong>${p.name}</strong><small>${p.breed} · ${p.age}${i===1?' · เริ่มจากข้อมูลว่าง':''}</small></span>${icon('arrow')}</button>`).join(''));break;
case'pet':if(!petData.some(p=>p.id===arg))break;closeModal();S.pet=arg;S.page='home';S.mode='normal';S.shareDraft=null;S.edit=null;S.amend=null;render();toast('กำลังดูแล '+pet().name);break;
case'trackers':openModal('เลือกเรื่องที่อยากติดตาม',[['vaccines','วัคซีน'],['meds','ยา & การให้ยา'],['appointments','นัดหมาย'],['weight','น้ำหนัก & BCS'],['labs','ผลแล็บ'],['allergies','แพ้ & การวินิจฉัย'],['insurance','ประกัน'],['nutrition','โภชนาการ']].map(([p,t])=>`<button class="list-item" data-act="track:${p}">${t}${icon('arrow')}</button>`).join(''));break;
case'track':closeModal();go(arg);break;
case'clear-filter':S.filter={type:'all',provenance:'all',from:'',to:''};render();break;
case'edit':case'amend':if(!guard()||!r||r.superseded)break;if(key==='edit'&&r.verified){toast('ต้นฉบับ Verified แก้ไขไม่ได้');break;}closeModal();S.formType=r.type;go('add');S[key==='edit'?'edit':'amend']=r.id;render();break;
case'delete':if(!guard()||!r||r.verified||r.superseded)break;openModal('ลบบันทึกนี้?',`<p>${esc(r.title)} จะถูกซ่อนจากประวัติ โดยระบบเก็บ audit และต้นฉบับตามนโยบาย</p>${btn('ยืนยันลบ','confirm-delete:'+r.id,'danger full')}`);break;
case'confirm-delete':if(!guard()||!r||r.verified)break;r.deleted=true;closeModal();log('DELETE /health/records/{id}',{record_id:r.id,soft_delete:true});render();toast('ซ่อนบันทึกจากประวัติแล้ว');break;
case'remind':if(!guard()||!r)break;r.reminder=!r.reminder;log('Reminder preference (proposed contract)',{record_id:r.id,enabled:r.reminder});render();break;
case'dose':if(!guard()||!r||r.status!=='active')break;const slot=r.id+today();if(S.adherence[slot])return toast('slot นี้บันทึกแล้ว ไม่สร้างซ้ำ');S.adherence[slot]=arg2;log('POST /medications/{id}/logs',{medication_id:r.id,slot:today(),status:arg2,idempotent:true});render();toast(arg2==='taken'?'บันทึกว่าให้ยาแล้ว':'บันทึกว่าข้ามครั้งนี้');break;
case'med-complete':case'med-stop':if(!guard()||!r||r.status!=='active')break;r.status=key==='med-stop'?'stopped':'completed';r.reminder=false;log('Medication status (proposed contract)',{record_id:r.id,status:r.status,future_reminders:false});render();break;
case'new-appointment':case'reschedule':if(!guard())break;const a=S.appointments.find(a=>a.id===arg&&a.pet===S.pet)||{};openModal(a.id?'เลื่อนนัดหมาย':'สร้างนัดหมาย',`<form id="appointment-form" data-id="${a.id||''}">${field('หัวข้อนัด','title','text',a.title||'',true)}${field('คลินิก / ผู้ให้บริการ','clinic','text',a.clinic||'',true)}${field('วันและเวลา','date','datetime-local',a.date||'2026-09-10T10:30',true)}<button class="primary full">บันทึกนัดหมาย</button></form>`);break;
case'appointment':if(!guard())break;const ap=S.appointments.find(a=>a.id===arg&&a.pet===S.pet);if(!ap||ap.status!=='scheduled')break;ap.status=arg2;ap.reminder=false;log('PATCH /appointments/{id}',{appointment_id:ap.id,status:arg2,reminders:false});render();toast('เปลี่ยนสถานะนัดแล้ว');break;
case'convert':if(!guard())break;const a2=S.appointments.find(a=>a.id===arg&&a.pet===S.pet);if(!a2||a2.status!=='completed')break;if(a2.linked)return detail(a2.linked);const rr={id:id('r'),pet:S.pet,type:'visit',title:a2.title,date:a2.date.slice(0,10),provenance:'Owner entered',appointment:a2.id,notes:'เชื่อมจากนัดหมายที่เสร็จสิ้น'};S.records.push(rr);a2.linked=rr.id;log('POST /pets/{petId}/health/records',{record_id:rr.id,appointment_id:a2.id,idempotent:true});render();toast('สร้างบันทึกและเชื่อมกับนัดแล้ว');break;
case'target':if(!guard())break;openModal('น้ำหนักเป้าหมาย',`<form id="target-form">${field('เป้าหมายที่เจ้าของ / Vet ระบุ (kg)','target','number',S.targets[S.pet]||'',true,'min="0.01" step="0.01"')}<button class="primary full">บันทึกเป้าหมาย</button></form>`);break;
case'resolve':if(!guard()||!r||r.verified)break;r.status=r.status==='resolved'?'active':'resolved';log('PATCH /health/records/{id}',{record_id:r.id,status:r.status});render();break;
case'scan':if(!guard())break;const d=S.docs.find(d=>d.id===arg&&d.pet===S.pet);if(!d||d.status!=='scanning')break;d.status=arg2;log('Simulated file_scan result',{document_id:d.id,status:d.status});render();break;
case'document':const doc=S.docs.find(d=>d.id===arg&&d.pet===S.pet);if(!doc||doc.status!=='ready')return toast('ไฟล์นี้ยังเปิดไม่ได้');openModal('รายละเอียดเอกสาร',`<span class="badge">Private document · ข้อมูลจำลอง</span><h3>${esc(doc.name)}</h3><p>เชื่อมกับ ${esc(S.records.find(r=>r.id===doc.record)?.title)}</p>${notice('เดโมนี้เก็บเฉพาะ metadata ไม่เก็บหรือแสดงเนื้อหาไฟล์จริง การตรวจสิทธิ์/scan/download ต้องเชื่อม backend ก่อนใช้งานจริง')}${btn('ปิด','close','primary full')}`);log('Authorized document view (simulated)',{document_id:doc.id});break;
case'delete-doc':if(!guard())break;const dd=S.docs.find(d=>d.id===arg&&d.pet===S.pet);if(dd?.verified)return toast('ลบไม่ได้: เอกสารเป็นหลักฐานของข้อมูลที่ยืนยันแล้ว');S.docs=S.docs.filter(d=>d!==dd);log('Document delete (proposed)',{document_id:arg});render();break;
case'confirm-share':if(!guard(true)||!S.shareDraft)break;if(!$('#consent-check')?.checked)return toast('กรุณายืนยันความยินยอมก่อนแชร์');const sh={...S.shareDraft,id:id('s'),status:'active'};S.shares.push(sh);S.shareDraft=null;closeModal();log('POST /pets/{petId}/shares',{grant_id:sh.id,pet_id:S.pet,consent:true,scope:'snapshot',records:sh.records,documents:sh.documents});go('shares');toast('สร้างสิทธิ์แชร์จำลองแล้ว');break;
case'recipient':recipientView(arg);break;
case'revoke':case'revoke-live':if(!guard(true))break;const s=S.shares.find(s=>s.id===arg&&s.pet===S.pet);if(!s)break;s.status='revoked';log('POST /shares/{id}/revoke',{grant_id:s.id,deny_immediately:true});render();if(key==='revoke-live')recipientView(s.id);toast('ถอนสิทธิ์แล้ว มุมมองผู้รับถูกปิด');break;
case'shared-doc':const sg=S.shares.find(s=>s.id===arg&&s.pet===S.pet);if(!sg||shareState(sg)!=='active'||!sg.documents.includes(arg2)){toast('ไม่อนุญาตให้อ่านเอกสาร');break;}const sd=S.docs.find(d=>d.id===arg2&&d.status==='ready');if(!sd)return toast('ไม่พบเอกสารที่เปิดได้');openModal('เอกสารที่แชร์',notice(esc(sd.name)+' · Metadata ตัวอย่างเท่านั้น')+btn('กลับมุมมองผู้รับ','recipient:'+sg.id,'secondary full'));log('Authorized gateway re-check',{grant_id:sg.id,document_id:sd.id});break;
case'advance':S.clock+=8*86400000;log('Demo clock advanced',{date:today(),expired_grants:S.shares.filter(s=>shareState(s)==='expired').length});render();toast('เวลาเดโม: '+dateLabel(today()));break;
case'qr-view':qrView(arg);break;
case'qr-rotate':if(!guard(true))break;S.qr[S.pet].version++;log('POST /pets/{petId}/emergency-card/rotate',{version:S.qr[S.pet].version});render();toast('Token เดิมถูกปิดแล้ว');break;
case'qr-revoke':if(!guard(true))break;S.qr[S.pet].active=false;log('Emergency token revoked (simulated)',{pet_id:S.pet});render();break;
case'verify':if(!guard(true))break;S.verification[S.pet]=arg;log('Phase 2 verification decision (simulated)',{pet_id:S.pet,status:arg,safe_summary_only:true});render();break;
case'ai-review':if(!guard())break;openModal('AI extraction · Phase 2',`<p>ข้อมูลเสนอจำลองจากเอกสาร ไม่มีการเรียกโมเดลหรืออ่านไฟล์</p><form id="ai-form">${field('ชื่อบันทึกที่ตรวจแล้ว','title','text','วัคซีนจากเอกสารจำลอง',true)}<label class="check-label"><input type="checkbox" name="confirmed" required> ฉันตรวจชื่อและวันที่ตัวอย่าง ${dateLabel(today())} แล้ว</label><button class="primary full">ยืนยันและบันทึก</button></form>${notice('ก่อน confirm ไม่มี structured record ถูกสร้าง')}`);break;
case'new-insurance':if(!guard())break;openModal('เพิ่มกรมธรรม์',`<form id="insurance-form">${field('บริษัทประกัน','provider','text','',true)}${field('เลขกรมธรรม์จำลอง','number','text','',true)}${field('สรุปความคุ้มครอง','coverage','text','',true)}${field('วันเริ่ม','effective','date',today(),true)}${field('วันหมดอายุ','expiry','date','',true)}<button class="primary full">บันทึกกรมธรรม์</button></form>`);break;
case'policy-reminder':if(!guard())break;const ins=S.insurance.find(p=>p.id===arg&&p.pet===S.pet);if(ins){ins.reminder=!ins.reminder;log('Insurance reminder preference',{policy_id:ins.id,enabled:ins.reminder});render();}break;
case'invite':if(!guard(true))break;openModal('เชิญผู้ช่วยดูแล',`<form id="invite-form">${field('ชื่อ / อีเมลจำลอง','name','text','',true)}${selectField('บทบาท','role',[['Viewer','Viewer · อ่านอย่างเดียว'],['Co-owner','Co-owner · เพิ่มบันทึก']],'Viewer')}<button class="primary full">เพิ่มสิทธิ์จำลอง</button></form>`);break;
case'remove-access':if(!guard(true))break;S.access=S.access.filter(a=>!(a.id===arg&&a.pet===S.pet));log('DELETE /pets/{petId}/access/{userId}',{grant:arg});render();break;
}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b&&!b.disabled)actions(b.dataset.act);const tab=e.target.closest('[data-doc]');if(tab){S.doc=tab.dataset.doc;renderDocs();}const mobile=e.target.closest('button[data-mobile]');if(mobile){document.body.dataset.mobile=mobile.dataset.mobile;$$('.mobile-switch button').forEach(b=>b.classList.toggle('active',b===mobile));}});
document.addEventListener('change',e=>{if(e.target.id==='demo-role'){closeModal();S.role=e.target.value;S.edit=null;S.amend=null;render();return;}if(e.target.id==='demo-state'){S.mode=e.target.value;render();return;}if(e.target.id==='record-type'){S.formType=e.target.value;render();return;}if(e.target.id==='f-preset'&&e.target.value!=='custom')$('#f-title').value=e.target.value;if(e.target.id.startsWith('filter-')){S.filter[e.target.id.slice(7)]=e.target.value;render();}});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(!f.reportValidity())return;const d=new FormData(f),v=Object.fromEntries(d.entries());if(!guard(['share-form','qr-form','invite-form'].includes(f.id)))return;
switch(f.id){
case'record-form':{const t=S.formType,old=S.records.find(r=>r.id===S.edit&&r.pet===S.pet),parent=S.records.find(r=>r.id===S.amend&&r.pet===S.pet);if(old?.verified)return toast('Verified original แก้ไม่ได้');if(v.end&&v.end<v.date)return toast('วันสิ้นสุดต้องไม่ก่อนวันเริ่ม');if(t==='lab'&&v.resultKind==='numeric'&&!Number.isFinite(Number(v.result)))return toast('ผลตรวจชนิดตัวเลขต้องเป็นตัวเลข');if(t==='lab'&&v.low!==''&&v.high!==''&&Number(v.low)>Number(v.high))return toast('ค่าต่ำสุดต้องไม่มากกว่าค่าสูงสุด');let r={...old,...v,id:old?.id||id('r'),pet:S.pet,type:t,provenance:'Owner entered',verified:false,status:old?.status||'active',reminder:d.has('reminder')};delete r.preset;if(t==='weight'){r.value=Number(v.value);r.title='บันทึกน้ำหนัก';}if(t==='lab'){r.result=v.resultKind==='numeric'?Number(v.result):v.result;r.low=v.low===''?null:Number(v.low);r.high=v.high===''?null:Number(v.high);}if(parent){r.parent=parent.id;parent.superseded=true;}if(old)Object.assign(old,r);else S.records.push(r);log(parent?'POST /health/records/{id}/amendments':old?'PATCH /health/records/{id}':'POST /pets/{petId}/health/records',{record_id:r.id,type:t,pet_id:S.pet,parent_record_id:r.parent||null,atomic_audit:true});S.edit=null;S.amend=null;go(t==='weight'?'weight':t==='medication'?'meds':t==='lab'?'labs':t==='vaccine'?'vaccines':'timeline');toast('บันทึกแล้ว · ประวัติอัปเดตทันที');break;}
case'appointment-form':{const old=S.appointments.find(a=>a.id===f.dataset.id&&a.pet===S.pet);if(old)Object.assign(old,v);else S.appointments.push({...v,id:id('a'),pet:S.pet,status:'scheduled',reminder:true});closeModal();log(old?'PATCH /appointments/{id}':'POST /pets/{petId}/appointments',{pet_id:S.pet,reminder_recalculated:true});render();break;}
case'target-form':S.targets[S.pet]=Number(v.target);closeModal();log('Health target update (proposed)',{pet_id:S.pet,target_kg:Number(v.target)});render();break;
case'upload-form':{const file=d.get('file');if(!file?.size)return toast('กรุณาเลือกไฟล์ที่มีเนื้อหา');const ext=file.name.split('.').pop().toLowerCase();if(!['pdf','jpg','jpeg','png'].includes(ext)||file.size>10*1024*1024||file.type&&!['application/pdf','image/jpeg','image/png'].includes(file.type))return toast('ไม่รับไฟล์นี้: ใช้ PDF/JPG/PNG ไม่เกิน 10 MB');const rec=S.records.find(r=>r.id===v.record&&r.pet===S.pet&&!r.deleted);if(!rec)return toast('เลือกบันทึกที่เข้าถึงได้ก่อน');if(rec.verified)return toast('ต้นฉบับยืนยันแล้ว: สร้าง amendment ก่อนเพิ่มหลักฐานใหม่');const doc={id:id('d'),pet:S.pet,record:v.record,name:file.name,size:Math.ceil(file.size/1024)+' KB',status:'scanning'};S.docs.push(doc);log('POST /pets/{petId}/documents (metadata demo)',{document_id:doc.id,quarantine:true,bytes_uploaded:false});render();toast('รับ metadata แล้ว ลองจำลองผล scan ได้');break;}
case'share-form':{const recordIds=d.getAll('records'),documents=d.getAll('documents');if(!recordIds.length&&!documents.length)return toast('เลือกอย่างน้อย 1 บันทึกหรือเอกสาร');const expires=new Date(v.expiry+'T23:59:59+07:00').getTime();if(expires<=S.clock)return toast('วันหมดอายุต้องอยู่ในอนาคต');S.shareDraft={pet:S.pet,recipient:v.recipient,records:recordIds,documents,expires};openModal('ตรวจสอบก่อนแชร์',`<div class="share-preview"><p>ผู้รับ: <strong>${esc(v.recipient)}</strong></p><p>สัตว์เลี้ยง: <strong>${pet().name}</strong></p><p>สิ้นสุด: ${dateLabel(v.expiry)}</p>${recordIds.map(rid=>'<p>✓ '+esc(S.records.find(r=>r.id===rid).title)+'</p>').join('')}${documents.map(did=>'<p>✓ เอกสาร '+esc(S.docs.find(d=>d.id===did).name)+'</p>').join('')}</div>${notice('เฉพาะ snapshot นี้ ไม่รวมข้อมูลใหม่หรือไฟล์อื่น')}<label class="check-label"><input type="checkbox" id="consent-check"> ฉันยินยอมให้ผู้รับอ่านข้อมูลที่เลือกจนถึงวันหมดอายุ</label>${btn('ยืนยันและสร้างสิทธิ์','confirm-share','primary full')}`);break;}
case'qr-form':{const fields=d.getAll('fields');if(!fields.length)return toast('เลือกข้อมูลบนบัตรอย่างน้อย 1 ช่อง');if(fields.includes('contact')&&!v.contact.trim())return toast('กรอกผู้ติดต่อหรือยกเลิกช่องผู้ติดต่อ');const old=qrConfig();S.qr[S.pet]={active:true,version:old.version+(old.active?0:1),fields,contact:v.contact};log('PUT /pets/{petId}/emergency-card',{pet_id:S.pet,fields,token_version:S.qr[S.pet].version});render();toast('บันทึกบัตรฉุกเฉินแล้ว');break;}
case'insurance-form':if(v.expiry<v.effective)return toast('วันสิ้นสุดต้องไม่ก่อนวันเริ่ม');S.insurance.push({...v,id:id('i'),pet:S.pet,reminder:true});closeModal();log('POST /pets/{petId}/insurance',{pet_id:S.pet,policy_number_logged:false});render();break;
case'nutrition-form':S.targets[S.pet]=Number(v.target);S.nutrition??={};S.nutrition[S.pet]={stage:v.stage,neutered:v.neutered};log('Nutrition context saved (demo)',{pet_id:S.pet,stage:v.stage,neutered:v.neutered,calculation:'policy not configured'});toast('บันทึกบริบทแล้ว · สูตรประมาณการยังรอนโยบาย');break;
case'invite-form':S.access.push({...v,id:id('p'),pet:S.pet});closeModal();log('POST /pets/{petId}/access',{pet_id:S.pet,role:v.role,notification_sent:false});render();break;
case'notify-form':{const prefs={offset:v.offset};for(let i=0;i<8;i++)prefs['n'+i]=d.has('n'+i);S.preferences[S.pet]=prefs;log('Reminder settings (proposed contract)',{pet_id:S.pet,offset_days:Number(v.offset),delivery:'simulated only'});toast('บันทึกการแจ้งเตือนแล้ว');break;}
case'ai-form':if(!d.has('confirmed'))return;const ar={id:id('r'),pet:S.pet,type:'vaccine',title:v.title,date:today(),provenance:'AI extracted · Human confirmed',confirmed:true,notes:'Phase 2 fixture · reviewed before save'};S.records.push(ar);closeModal();log('Phase 2 extraction confirmed',{record_id:ar.id,human_confirmed:true,real_ai:false});go('timeline');toast('สร้างบันทึกหลังยืนยันแล้ว');break;
}});
// Inspector: architecture and draft API contracts are explanatory, never network requests.
const flows={
home:['ภาพรวมที่บอกสิ่งถัดไป','FR-001 / 034','GET /pets/{petId}/health/summary','เปิด Health ของ pet ที่เลือก','ตรวจ pet_access และ role','รวมกำหนดการ / records / active shares','Next Action + freshness โดยไม่มี Health Score','ลองเพิ่มน้ำหนัก แล้วกลับหน้า Home ดูวันที่ล่าสุด'],
timeline:['ทุกเหตุการณ์ มีแหล่งที่มา','FR-003 / 005 / 039 / 040','GET /pets/{petId}/health/records','เลือกประเภท / วันที่ / provenance','ตรวจ resource scope ก่อน query','health_records + typed details + revision','แสดงเฉพาะสิทธิ์และ filter ที่เลือก','เปิด Vet verified → สร้าง amendment → ดูต้นฉบับย้อนหลัง'],
add:['บันทึกครั้งเดียว เชื่อมทั้งระบบ','FR-004 / 005 · NFR-002','POST /pets/{petId}/health/records','กรอก structured fields','Authorize + validate + idempotency','Transaction: record + typed data + audit','Timeline / tracker แสดงข้อมูลใหม่','ลองกรอกวันสิ้นสุดก่อนวันเริ่ม และเพิ่มข้อมูลที่ถูกต้อง'],
vaccines:['วันสำคัญที่คุณกำหนดเอง','FR-006–008 · BR-010','POST /pets/{petId}/vaccines','เลือก preset / custom + next due','Validate species, date, role','health_records + vaccines + reminders','ประวัติและกำหนดถัดไป แก้วันที่ได้','เพิ่มวัคซีนแบบไม่มี due ได้ · ไม่มี reminder จาก due ที่ว่าง'],
meds:['หนึ่ง slot หนึ่งบันทึก','FR-009 · NFR-002','POST /medications/{id}/logs','บันทึก Taken / Skipped','ตรวจ write permission + schedule slot','medication_logs unique slot; audit','สำเร็จแล้วกดซ้ำไม่สร้างรายการเพิ่ม','ลองให้แล้ว → ปุ่ม slot ถูกปิด → หยุดยาปิด future reminders'],
appointments:['จากวันนัด สู่ประวัติ','FR-012 / 013','PATCH /appointments/{id}','Create / reschedule / complete','Validate transition and ownership','appointments + recalculate reminders','Completed → เลือกสร้าง linked record','กดสร้างบันทึกซ้ำไม่สร้าง record ที่สอง'],
weight:['เห็นแนวโน้ม โดยไม่ตีความสุขภาพ','FR-014–017 · BR-007','POST /pets/{petId}/weight','กรอก kg + measured date','Validate weight > 0','Sort valid measurements by measured_at','% change จาก previous valid measurement','ลองเพิ่มย้อนหลัง ดูกราฟ/เปอร์เซ็นต์เปลี่ยนตามลำดับเวลา'],
labs:['เก็บผลตามรายงานต้นทาง','FR-018–021 · BR-006','POST /pets/{petId}/labs','กรอก result / unit / supplied range','Validate numeric / text / range','lab_panels + lab_results + source refs','High / Low มีข้อความ ไม่อาศัยสีอย่างเดียว','ลองเว้น reference range จะไม่ infer ว่าปกติ'],
allergies:['ข้อมูลสำคัญ พร้อม provenance','FR-010 / 011 / 024','POST /pets/{petId}/health/records','เพิ่ม allergen / diagnosis','Authorize mutable vs immutable','health_records + allergies / diagnoses','Active fields เป็น candidate ให้ Emergency Card','ตั้ง allergy เป็นไม่ใช้งาน แล้วดู emergency view'],
documents:['ไฟล์เป็นส่วนตัวตั้งแต่เริ่ม','FR-020 / 021 · BR-019 / 020','POST /pets/{petId}/documents','เลือกไฟล์ + linked record','Type / size → quarantine → scan','Private object bytes + DB metadata','Ready จึงให้ authorized gateway เปิดได้','ลอง scan reject และลบ evidence ที่ Verified → ปฏิเสธ'],
share:['ก่อนแชร์ ต้องเห็นขอบเขต','FR-022 / 023 · DEC-03','POST /pets/{petId}/shares','Recipient → snapshot → expiry → preview','ตรวจ Owner + explicit consent','share_grants + durable consent audit','ผู้รับอ่านเฉพาะ record / document IDs','ลองยืนยันโดยไม่ติ๊ก consent → ยังไม่สร้าง grant'],
shares:['หยุดเข้าถึงได้ เมื่อเปลี่ยนใจ','FR-034 · BR-013','POST /shares/{id}/revoke','Owner revoke หรือ expiry','ทุก read/download ตรวจ grant ใหม่','Revoke + audit; invalidate scope-aware cache','ผู้รับถูก deny ทันที ไม่รอ signed URL TTL','เปิด recipient → จำลอง Owner revoke → ไม่มีข้อมูลแสดง'],
verification:['ยืนยันแยกประเภท ไม่ใช่คะแนนสุขภาพ','FR-031–033 / 038 · DEC-01','POST /verifications/{id}/decision','Request → Vet with consent reviews','Professional permission + policy + evidence','Pinned revision + audit + safe summary event','Matching เห็นเฉพาะ status; expiry ห้าม active','Phase 2 จำลอง pending → verified → expired; AI ต้อง confirm'],
emergency:['เท่าที่จำเป็น ในเวลาฉุกเฉิน','FR-024 / 025 · BR-014','PUT /pets/{petId}/emergency-card','Owner เลือก fields + เปิด token','Token active/version gate ไม่ต้อง login','emergency_profiles whitelist projection','เฉพาะ allergy / active meds / contact','Rotate token → ลอง token เก่า → deny; QR ภาพเป็น simulation'],
insurance:['ข้อมูลกรมธรรม์ที่ไม่เผยต่อเอง','FR-026 · BR-014','POST /pets/{petId}/insurance','กรอก policy / dates / summary','Authorize; protect policy number','insurance_policies + expiry reminder','ติดตามวันสิ้นสุด ไม่รวมบน QR','เพิ่มกรมธรรม์ แล้วเลื่อนเวลาเดโมเพื่อดู expiry'],
nutrition:['บริบทพร้อม ก่อนมีสูตรจริง','FR-027 / 028 · DEC-12','GET /pets/{petId}/nutrition/estimate','Target weight + life stage + neutered','ตรวจ policy version ที่อนุมัติ','Context inputs; no ungoverned calculation','ยังไม่คำนวณเมื่อ formula ยังไม่กำหนด','เดโมบันทึกบริบท แต่ไม่สร้างตัวเลขแคลอรีขึ้นเอง'],
access:['สิทธิ์ของคน ผูกกับสัตว์แต่ละตัว','FR-029 / 030 · DEC-04','POST /pets/{petId}/access','Owner เชิญ Co-owner / Viewer','Owner management; scoped role grant','pet_access + audit','Viewer อ่านอย่างเดียว; Co-owner share deny','เปลี่ยนบทบาทในตัวทดลอง แล้วดูปุ่มและ write guard'],
notifications:['เตือนตามที่เจ้าของตั้งไว้','FR-008 / 035 · NFR-005','Reminder settings contract: proposed','Event enable + offset + channel','Validate rule + timezone','reminders → scheduler → dedup delivery','Notification ไม่สร้าง medication log','เดโมบันทึก preference ไม่ส่ง email หรือ push จริง']
};
function flowNodes(nodes){return `<div class="diagram">${nodes.map((n,i)=>`${i?'<div class="flow-arrow" aria-hidden="true">↓</div>':''}<div class="flow-node ${['client','api','db','client'][i%4]}"><b>${['01 · USER ACTION','02 · PERMISSION & RULES','03 · DATA & TRANSACTION','04 · RESULT'][i%4]}</b>${esc(n)}</div>`).join('')}</div>`;}
function renderDocs(){const f=flows[S.page];$$('[data-doc]').forEach(b=>b.classList.toggle('active',b.dataset.doc===S.doc));let html='';if(S.doc==='flow'){html=`<span class="eyebrow">HEALTH CARE / ${$('#screen-position').textContent}</span><h2>${f[0]}</h2><p class="lead">${f[3]} → ${f[6]}</p><span class="ref">${f[1]}</span>${flowNodes(f.slice(3,7))}<h3>API contract ตาม PRD / ข้อเสนอ</h3><pre>${esc(f[2])}</pre><h3>ลอง flow นี้</h3><p class="test-note">${f[7]}</p>${notice('แผนภาพอธิบายระบบเป้าหมาย การกดใน HTML ใช้ข้อมูลจำลองและ write guards ฝั่ง client เท่านั้น')}`;}else if(S.doc==='atlas'){html=`<h2>ทุกหน้ามีหน้าที่<br>ทุก action มีที่มา</h2><p>18 screens เชื่อมกันด้วย pet_id เดียว ลองเลือกหน้าที่ต้องการเพื่อเปิด UI และ flow</p>`+screens.map((s,i)=>`<button class="atlas-row" data-act="go:${s[0]}"><span class="ref">HC-${String(i+1).padStart(2,'0')}</span> ${s[1]}<small>${flows[s[0]][3]} → ${flows[s[0]][6]}</small></button>`).join('');}else{html=`<span class="eyebrow">SYSTEM OVERVIEW</span><h2>One pet.<br>One health history.</h2><p>สถาปัตยกรรมเป้าหมายตาม PRD §16 · modular backend โดยไม่เปิด raw health data ให้ Matching</p>${flowNodes(['Next.js / React · Owner / Co-owner / Viewer','FastAPI · authentication + resource authorization','PostgreSQL source of truth + private S3 + worker queue','Health views + Matching safe summary only'])}<h3>Logical data relationships</h3><div class="schema-grid">${[['pets','1 → N health_records<br>1 → N pet_access'],['health_records','1 → typed detail<br>parent → amendment revision'],['documents','record_id → health_records<br>private storage_key'],['share_grants','pet_id + recipient<br>snapshot scope + expiry'],['verification_records','evidence pins revision<br>safe summary → Matching'],['reminders','entity + rule + timezone<br>worker → notification']].map(([k,v])=>`<div><b>${k}</b><small>${v}</small></div>`).join('')}</div><h3>การแยกขอบเขตข้อมูล</h3><p>UI → authorization → structured data / private file gateway<br>QR → token gate → configured fields เท่านั้น<br>Verification → safe summary → Matching<br>AI Phase 2 → field review → confirm → save</p>${notice('DEC-01: verification release ยังรอตัดสิน · DEC-03: ใช้ snapshot ในเดโม · DEC-12: ไม่มี medical threshold หรือสูตร nutrition ที่เดาเอง',true)}<h3>Prototype boundaries</h3><p>In-memory เท่านั้น · ไม่มี backend, storage, malware scan, notification delivery, Vet identity หรือ AI จริง · QR เป็นภาพจำลองพร้อมปุ่มเปิดมุมมองผู้รับ</p>`;}
html+=`<h3>Live interaction trace <span class="ref">จำลอง</span></h3><p>เหตุการณ์ล่าสุดจากการกดใช้งาน · ไม่ใช่ network request</p>${S.logs.length?S.logs.slice(0,5).map(l=>`<div class="log-entry"><small>${l.at} · ${esc(l.action)}</small><code>${esc(JSON.stringify(l.detail))}</code></div>`).join(''):'<div class="notice">ลองเพิ่มน้ำหนัก หรือแชร์ข้อมูล แล้วดู trace ที่นี่</div>'}`;$('#doc-content').innerHTML=html;}
render();
